language: python

notifications:
  email: false
  
branches:
only:
  - master

install:
  - pip install -r requirements.txt 

script:
  - python -m unittest discover
  - cd plotting
  - python plot_phad_ablation.py
  - python plot_tuning.py
