language: python

notifications:
  email: false
  
branches:
only:
  - master

install:
  - pip install -r requirements.txt 
  - sudo apt-get -qq update
  - sudo apt-get install -y wget gunzip

before_script:
  - cd data
  - ./download_data.sh
  - cd ..

script:
  - python -m unittest discover
  - cd plotting
  - python plot_phad_ablation.py
  - python plot_tuning.py
